b2c/sfsc/src/objects/AccountFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This custom setting hold field mapping between commerce cloud profile and person type account in SFSC</description>
    <fields>
        <fullName>CC_Attribute__c</fullName>
        <description>This field holds CC Attribute Name</description>
        <inlineHelpText>This field holds CC Attribute Name</inlineHelpText>
        <label>CC Attribute</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Patch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be patched in commerce cloud from CRM or not</description>
        <inlineHelpText>This setting check if this attribute will be patched in commerce cloud from CRM or not</inlineHelpText>
        <label>Enable Patch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be synchronised from commerce cloud or not</description>
        <inlineHelpText>This setting check if this attribute will be synchronised from commerce cloud or not</inlineHelpText>
        <label>Enable Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <description>This field holds service cloud field api name which is mapped to commerce cloud attributes.</description>
        <inlineHelpText>This field holds service cloud field api name which is mapped to commerce cloud attributes.</inlineHelpText>
        <label>Field Api Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AccountFieldMapping</label>
</CustomObject>

b2c/sfsc/src/objects/AddressFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This object holds attribute mapping between commerce cloud address attributes and NSSCCConnector__Address__c attributes</description>
    <fields>
        <fullName>CC_Attribute__c</fullName>
        <description>This field holds CC Attribute Name</description>
        <inlineHelpText>This field holds CC Attribute Name</inlineHelpText>
        <label>CC Attribute</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Patch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be patched in commerce cloud from CRM or not</description>
        <inlineHelpText>This setting check if this attribute will be patched in commerce cloud from CRM or not</inlineHelpText>
        <label>Enable Patch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be synchronised from commerce cloud or not</description>
        <inlineHelpText>This setting check if this attribute will be synchronised from commerce cloud or not</inlineHelpText>
        <label>Enable Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <description>This field holds salesforce object attribute api name</description>
        <inlineHelpText>This field holds salesforce object attribute api name</inlineHelpText>
        <label>Field Api Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>AddressFieldMapping</label>
</CustomObject>

b2c/sfsc/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>Case_Sub_Type__c</fullName>
        <description>This field holds case sub type value coming from Salesforce Commerce Cloud.</description>
        <inlineHelpText>This field holds case sub type value coming from Salesforce Commerce Cloud.</inlineHelpText>
        <label>Case Sub Type</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Where is my order</fullName>
                </value>
                <value>
                    <fullName>What is my order status</fullName>
                </value>
                <value>
                    <fullName>Complaint</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Id__c</fullName>
        <description>This field holds salesforce commerce cloud customer id. Usually case will be connected to contact but this field is to cover edge cases.</description>
        <inlineHelpText>This field holds salesforce commerce cloud customer id. Usually case will be connected to contact but this field is to cover edge cases.</inlineHelpText>
        <label>SFCC Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds commerce cloud customer number</description>
        <inlineHelpText>This field holds commerce cloud customer number</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFCC_Order_No__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Order No. This is optional field</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Order No. This is optional field</inlineHelpText>
        <label>SFCC Order No</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

b2c/sfsc/src/objects/CaseFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting holds field mapping between Salesforce Commerce Cloud Case Object and Service Cloud Case Object. This mapping is used in Rest Apex wrapper class</description>
    <fields>
        <fullName>CC_Attribute__c</fullName>
        <description>This field holds CC Attribute Name</description>
        <inlineHelpText>This field holds CC Attribute Name</inlineHelpText>
        <label>CC Attribute</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Patch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be patched in commerce cloud from CRM or not</description>
        <inlineHelpText>This setting check if this attribute will be patched in commerce cloud from CRM or not</inlineHelpText>
        <label>Enable Patch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be synchronised from commerce cloud or not</description>
        <inlineHelpText>This setting check if this attribute will be synchronised from commerce cloud or not</inlineHelpText>
        <label>Enable Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <description>This Field holds mapping between Service Cloud Object Attributes with Commerce Cloud request object attributes</description>
        <inlineHelpText>This Field holds mapping between Service Cloud Object Attributes with Commerce Cloud request object attributes</inlineHelpText>
        <label>Field Api Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>CaseFieldMapping</label>
</CustomObject>

b2c/sfsc/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SFCC_Customer_Id__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Customer ID.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Customer ID.</inlineHelpText>
        <label>SFCC Customer Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud customer number.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud customer number.</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

b2c/sfsc/src/objects/ContactFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting holds field mapping between Salesforce Commerce Cloud Contact Object and Service Cloud Customer/Customer Profile Object. This mapping is used in Rest Apex wrapper class</description>
    <fields>
        <fullName>CC_Attribute__c</fullName>
        <description>This field holds CC Attribute Name</description>
        <inlineHelpText>This field holds CC Attribute Name</inlineHelpText>
        <label>CC Attribute</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Patch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be patched in commerce cloud from CRM or not</description>
        <inlineHelpText>This setting check if this attribute will be patched in commerce cloud from CRM or not</inlineHelpText>
        <label>Enable Patch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be synchronised from commerce cloud or not</description>
        <inlineHelpText>This setting check if this attribute will be synchronised from commerce cloud or not</inlineHelpText>
        <label>Enable Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <description>This Field holds mapping between Service Cloud Object Attributes mapping with Commerce Cloud request object attributes</description>
        <inlineHelpText>This Field holds mapping between Service Cloud Object Attributes mapping with Commerce Cloud request object attributes</inlineHelpText>
        <label>Field Api Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>ContactFieldMapping</label>
</CustomObject>

b2c/sfsc/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>Order_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This field holds order relationship with contact.</description>
        <inlineHelpText>This field holds order relationship with contact.</inlineHelpText>
        <label>Order Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Orders</relationshipLabel>
        <relationshipName>SCCOrders</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Order_SCCSync_Status__c</fullName>
        <description>This field holds Order Synchronised status with Salesforce Commerce Cloud.</description>
        <inlineHelpText>This field holds Order Synchronised status with Salesforce Commerce Cloud.</inlineHelpText>
        <label>Order SCC Sync Status</label>
        <required>true</required>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Synchronised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>SFCC_Order_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Order Number.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Order Number.</inlineHelpText>
        <label>Customer Order Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SFCC_Order_Total__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Order total value.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Order total value.</inlineHelpText>
        <label>Order Total</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

b2c/sfsc/src/objects/OrderFieldMapping__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>This Custom Setting holds field mapping between Salesforce Commerce Cloud Order Object and Service Cloud Order Object. This mapping is used in Rest Apex wrapper class to create order header in Salesforce.</description>
    <fields>
        <fullName>CC_Attribute__c</fullName>
        <description>This field holds CC Attribute Name</description>
        <inlineHelpText>This field holds CC Attribute Name</inlineHelpText>
        <label>CC Attribute</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Enable_Patch__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be patched in commerce cloud from CRM or not</description>
        <inlineHelpText>This setting check if this attribute will be patched in commerce cloud from CRM or not</inlineHelpText>
        <label>Enable Patch</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Enable_Sync__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This setting check if this attribute will be synchronised from commerce cloud or not</description>
        <inlineHelpText>This setting check if this attribute will be synchronised from commerce cloud or not</inlineHelpText>
        <label>Enable Sync</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Field_Api_Name__c</fullName>
        <description>This field holds service cloud field api name which is mapped to commerce cloud attributes.</description>
        <inlineHelpText>This field holds service cloud field api name which is mapped to commerce cloud attributes.</inlineHelpText>
        <label>Field Api Name</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>OrderFieldMapping</label>
</CustomObject>

b2c/sfsc/src/classes/SCCConnectorPostInstallScript.cls
global class SCCConnectorPostInstallScript implements InstallHandler {
    global void onInstall(InstallContext context) {
        insertCustomSettingsData();
    }

    public static void insertCustomSettingsData(){
        insertAccountFieldMapping();
        insertAddressFieldMapping();
        insertContactFieldMapping();
        insertCaseFieldMapping();
        insertOrderFieldMapping();
        //This fails intallation hence commented.
        createDefaultAccount();
    }

    /*
    *This method inserts Contact object field mapping between salesforce and commerce cloud
    *
    */
    private static void insertAccountFieldMapping(){
        List<AccountFieldMapping__c> accountFieldMappings = AccountFieldMapping__c.getAll().values();
        Delete accountFieldMappings;
        upsert new AccountFieldMapping__c(Name = 'username', CC_Attribute__c = 'credentials.login', Field_Api_Name__c  = 'CC_Username__pc', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AccountFieldMapping__c(Name = 'customer_no', CC_Attribute__c = 'customer_no', Field_Api_Name__c  = 'SFCC_Customer_Number__pc', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new AccountFieldMapping__c(Name = 'customer_id', CC_Attribute__c = 'customer_id', Field_Api_Name__c  = 'SFCC_Customer_Id__pc', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new AccountFieldMapping__c(Name = 'first_name', CC_Attribute__c = 'first_name', Field_Api_Name__c  = 'FirstName', Enable_Patch__c = true, Enable_Sync__c = true);
        upsert new AccountFieldMapping__c(Name = 'last_name', CC_Attribute__c = 'last_name', Field_Api_Name__c  = 'LastName', Enable_Patch__c = true, Enable_Sync__c = true);
        upsert new AccountFieldMapping__c(Name = 'email', CC_Attribute__c = 'email', Field_Api_Name__c  = 'personEmail', Enable_Patch__c = true, Enable_Sync__c = true);
        upsert new AccountFieldMapping__c(Name = 'enabled', CC_Attribute__c = 'credentials.enabled', Field_Api_Name__c  = 'Active__c', Enable_Patch__c = true, Enable_Sync__c = true);
        upsert new AccountFieldMapping__c(Name = 'phone_home', CC_Attribute__c = 'phone_home', Field_Api_Name__c  = 'PersonHomePhone', Enable_Patch__c = true, Enable_Sync__c = true);
    }

    /*
    *This method inserts Contact object field mapping between salesforce and commerce cloud
    *
    */
    private static void insertAddressFieldMapping(){
        List<AddressFieldMapping__c> addressFieldMappings = AddressFieldMapping__c.getAll().values();
        Delete addressFieldMappings;
        upsert new AddressFieldMapping__c(Name = 'address1', CC_Attribute__c = 'address1', Field_Api_Name__c  = 'Address_Line_1__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'address2', CC_Attribute__c = 'address2', Field_Api_Name__c  = 'Address_Line_2__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'address_id', CC_Attribute__c = 'address_id', Field_Api_Name__c  = 'Name', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'city', CC_Attribute__c = 'city', Field_Api_Name__c  = 'City__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'state', CC_Attribute__c = 'state', Field_Api_Name__c  = 'State__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'country', CC_Attribute__c = 'country', Field_Api_Name__c  = 'Country__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'first_name', CC_Attribute__c = 'first_name', Field_Api_Name__c  = 'First_Name__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'last_name', CC_Attribute__c = 'last_name', Field_Api_Name__c  = 'Last_Name__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'full_name', CC_Attribute__c = 'full_name', Field_Api_Name__c  = 'Full_Name__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'phone', CC_Attribute__c = 'phone', Field_Api_Name__c  = 'Phone__c', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new AddressFieldMapping__c(Name = 'postal_code', CC_Attribute__c = 'postal_code', Field_Api_Name__c  = 'Postal_Code__c', Enable_Patch__c = false, Enable_Sync__c = true);
    }

    /*
    *This method inserts Contact object field mapping between salesforce and commerce cloud
    *
    */
    private static void insertContactFieldMapping(){
        List<ContactFieldMapping__c> contactFieldMappings = ContactFieldMapping__c.getAll().values();
        Delete contactFieldMappings;
        upsert new ContactFieldMapping__c(Name = 'customer_no', CC_Attribute__c = 'customer_no', Field_Api_Name__c  = 'SFCC_Customer_Number__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new ContactFieldMapping__c(Name = 'customer_id', CC_Attribute__c = 'customer_id', Field_Api_Name__c  = 'SFCC_Customer_Id__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new ContactFieldMapping__c(Name = 'first_name', CC_Attribute__c = 'first_name', Field_Api_Name__c  = 'FirstName', Enable_Patch__c = true, Enable_Sync__c = true);
        upsert new ContactFieldMapping__c(Name = 'last_name', CC_Attribute__c = 'last_name', Field_Api_Name__c  = 'LastName', Enable_Patch__c = true, Enable_Sync__c = true);
        upsert new ContactFieldMapping__c(Name = 'email', CC_Attribute__c = 'email', Field_Api_Name__c  = 'Email', Enable_Patch__c = true, Enable_Sync__c = true);
    }

    /*
    *This method inserts Order object field mapping between salesforce and commerce cloud
    *
    */
    private static void insertOrderFieldMapping(){
        List<OrderFieldMapping__c> orderFieldMappings = OrderFieldMapping__c.getAll().values();
        Delete orderFieldMappings;
        upsert new OrderFieldMapping__c(Name = 'crmcontact_Id', CC_Attribute__c = 'crmcontact_Id', Field_Api_Name__c  = 'Order_Contact__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'order_no', CC_Attribute__c = 'order_no', Field_Api_Name__c  = 'SFCC_Order_Number__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'order_total', CC_Attribute__c = 'order_total', Field_Api_Name__c  = 'SFCC_Order_Total__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'scc_sync_status', CC_Attribute__c = 'scc_sync_status', Field_Api_Name__c  = 'Order_SCCSync_Status__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'status', CC_Attribute__c = 'status', Field_Api_Name__c  = 'Status', Enable_Patch__c = false, Enable_Sync__c = true);
        upsert new OrderFieldMapping__c(Name = 'billing_street', CC_Attribute__c = 'billing_street', Field_Api_Name__c  = 'BillingStreet', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'billing_city', CC_Attribute__c = 'billing_city', Field_Api_Name__c  = 'BillingCity', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'billing_state', CC_Attribute__c = 'billing_state', Field_Api_Name__c  = 'BillingState', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'blling_country', CC_Attribute__c = 'billing_country', Field_Api_Name__c  = 'BillingCountry', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'billing_postal_code', CC_Attribute__c = 'billing_postal_code', Field_Api_Name__c  = 'BillingPostalCode', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'shipping_street', CC_Attribute__c = 'shipping_street', Field_Api_Name__c  = 'ShippingStreet', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'shipping_city', CC_Attribute__c = 'shipping_city', Field_Api_Name__c  = 'ShippingCity', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'shipping_state', CC_Attribute__c = 'shipping_state', Field_Api_Name__c  = 'ShippingState', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'shipping_country', CC_Attribute__c = 'shipping_country', Field_Api_Name__c  = 'ShippingCountry', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new OrderFieldMapping__c(Name = 'shipping_postal_code', CC_Attribute__c = 'shipping_postal_code', Field_Api_Name__c  = 'ShippingPostalCode', Enable_Patch__c = false, Enable_Sync__c = false);
    }

    /*
    *This method inserts Case object field mapping between salesforce and commerce cloud
    *
    */
    private static void insertCaseFieldMapping(){
        List<CaseFieldMapping__c> caseFieldMappings = CaseFieldMapping__c.getAll().values();
        Delete caseFieldMappings;
        upsert new CaseFieldMapping__c(Name = 'case_sub_type', CC_Attribute__c = 'case_sub_type', Field_Api_Name__c  = 'Case_Sub_Type__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'case_type', CC_Attribute__c = 'case_type', Field_Api_Name__c  = 'Type', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'contact_id', CC_Attribute__c = 'contact_id', Field_Api_Name__c  = 'AccountId', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'customer_id', CC_Attribute__c = 'customer_id', Field_Api_Name__c  = 'SFCC_Customer_Id__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'description', CC_Attribute__c = 'description', Field_Api_Name__c  = 'Description', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'email', CC_Attribute__c = 'email', Field_Api_Name__c  = 'SuppliedEmail', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'first_name', CC_Attribute__c = 'first_name', Field_Api_Name__c  = 'SuppliedName', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'last_name', CC_Attribute__c = 'last_name', Field_Api_Name__c  = 'SuppliedLastName__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'order_no', CC_Attribute__c = 'order_no', Field_Api_Name__c  = 'SFCC_Order_No__c', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'phone', CC_Attribute__c = 'phone', Field_Api_Name__c  = 'SuppliedPhone', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'subject', CC_Attribute__c = 'subject', Field_Api_Name__c  = 'Subject', Enable_Patch__c = false, Enable_Sync__c = false);
        upsert new CaseFieldMapping__c(Name = 'sfcc_order_id', CC_Attribute__c = 'sfcc_order_id', Field_Api_Name__c  = 'Order__c', Enable_Patch__c = false, Enable_Sync__c = false);
    }

    /*
    *Create default account for Salesforce commerce cloud.
    *
    */
    private static void createDefaultAccount(){
        RecordType recordType = [SELECT Id FROM RecordType WHERE SobjectType='Account' AND Name = 'Business Account'];
        List<Account> defaultAccountList = [Select Id from Account where Name ='Default'];
        if(defaultAccountList.isEmpty()){
            Account record = new Account();
            record.Name = 'Default';
            record.recordTypeId = recordType.Id;
            Database.insert(record, true);
        }
    }

    public static void insertCustomOrderStatus(){
        Schema.DescribeFieldResult fieldResult = Order.Status.getDescribe();
        List<Schema.PicklistEntry> ple = fieldResult.getPicklistValues();
    }
}