b2c/sfsc/src/objects/Address__c.object
<CustomObject>
    <description>This object holds contact address for customer registered on commerce cloud.</description>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Commerce cloud address contact.</description>
        <inlineHelpText>Commerce cloud address contact.</inlineHelpText>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Addresses</relationshipLabel>
        <relationshipName>SCCAddresses</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>from_SFCC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Holds if this case is from Commerce Cloud or not</description>
        <inlineHelpText>Holds if this case is from Commerce Cloud or not</inlineHelpText>
        <label>from SFCC</label>
        <type>Checkbox</type>
    </fields>
    <label>Address</label>
    <nameField>
        <label>Address Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

b2c/sfsc/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Contact_Status__c</fullName>
        <description>This field hold contact status when its created, updated from Salesforce Commerce Cloud.</description>
        <inlineHelpText>This field hold contact status when its created, updated from Salesforce Commerce Cloud.</inlineHelpText>
        <label>Contact SCC Sync Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Created</fullName>
                </value>
                <value>
                    <fullName>Updated</fullName>
                </value>
                <value>
                    <fullName>Synchronised</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>From_SFCC__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field holds value if Contact is created from Salesforce Commerce Cloud or not.</description>
        <inlineHelpText>This field holds value if Contact is created from Salesforce Commerce Cloud or not.</inlineHelpText>
        <label>From SFCC</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Id__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Customer ID.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Customer ID.</inlineHelpText>
        <label>SFCC Customer Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud customer number.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud customer number.</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

b2c/sfsc/src/classes/SCCContactImpl.cls
/**
* Impl class of contact that implements interface
*
*
* @author  Neeraj Yadav
* @version 1.0
* @since   2018-01-15
*/
public class SCCContactImpl implements SCCSynchronisedInterface {

    //related contact record
    public static Contact contactRecord;
    //customer number for commerce cloud
    public static String customerNo                     {get; set;}
    //customer number for commerce cloud
    public static String customerId                     {get; set;}
    //json map after deserialization
    public static Map<String, Object> jsonMap           {get; set;}


    /**
    * This method used for implementing related operations and update object status as Synchronised for contact records
    * @param contactObj: SObject
    * @return None.
    */
    public void continueWithObject(SObject contactObj) {

        syncContact(contactObj.Id);
    }

    public static Boolean syncContact(String contactId){
        SCCFileLogger logger = SCCFileLogger.getInstance();
        try {
            Map<String, SObject> contactFieldMappings = SCCUtilityClass.getAllCustomSettingValues('Contact', logger);
            contactRecord = [SELECT Id, FirstName, LastName, Email, SFCC_Customer_Id__c, SFCC_Customer_Number__c FROM Contact WHERE Id =: contactId];
            customerNo = contactRecord.SFCC_Customer_Number__c;
            customerId = contactRecord.SFCC_Customer_Id__c;
            //List<SCCCustomerWrapper> returnList = new List<SCCCustomerWrapper>();
            String resBody = SCCCommerceCloudConnect.getCustomerDetails(customerNo, SCCCommerceCloudConnect.connectToCommerceCloud());
            String addressBody = SCCCommerceCloudConnect.getAddressDetails(customerNo, SCCCommerceCloudConnect.connectToCommerceCloud());
            logger.debug('SCCContactImpl.syncContact','resBody: ' + resBody + ' addressBody: '+addressBody);
            jsonMap = (Map<String, Object>)System.JSON.deserializeUntyped(resBody);
            Map<String, Object> addressJsonMap = (Map<String, Object>)System.JSON.deserializeUntyped(addressBody);
            Contact updatedContact = (Contact)SCCUtilityClass.initializeObject(jsonMap, 'Contact', contactFieldMappings, logger);
            updatedContact.Contact_Status__c = 'Synchronised';
            updatedContact.from_SFCC__c = true;
            updatedContact.Id = contactRecord.Id;
            Database.update(updatedContact, true);
            if(addressJsonMap.containsKey('data') &&
               !((List<Object>)addressJsonMap.get('data')).isEmpty()){
                upsertAddressBook(updatedContact.Id, (List<Object>)addressJsonMap.get('data'));
            }
            return true;
        } catch(Exception e) {
            logger.error('SCCContactRefreshComponentController.syncContact', 'Exception message : '
                         + e.getMessage() + ' StackTrack '+ e.getStackTraceString());
            return false;
        }finally{
            logger.flush();
        }
    }

    public static void upsertAddressBook(Id recordId, List<Object> addressJsonMap) {
        SCCFileLogger logger = SCCFileLogger.getInstance();
		try {
			logger.debug('SCCAccountImpl.upsertAddressBook',' recordId: ' + recordId + ' addressJsonMap: ' + addressJsonMap);
			Map<String, SObject> addressFieldMappings = SCCUtilityClass.getAllCustomSettingValues('Address', logger);
            List<Address__c> contactAddressList = new List<Address__c>();
			for(Object obj : addressJsonMap) {
				Map<String, Object> tempMap = (Map<String, Object>)obj;
				Address__c record = (Address__c)SCCUtilityClass.initializeObject(tempMap, 'Address__c', addressFieldMappings, logger);
				Address__c address = SCCUtilityClass.getContactAddress(String.valueOf(tempMap.get('address_id')), recordId, null);
                if(address != null && address.Id != null){
                    record.Id = address.Id;
                }
                record.Contact__c = recordId;
				record.from_SFCC__c = true;
				contactAddressList.add(record);
			}
			Database.upsert(contactAddressList);
        } catch(Exception e) {
            logger.error('SCCAccountImpl.upsertAddressBook', 'Exception message : '
                         + e.getMessage() + ' StackTrack '+ e.getStackTraceString());
        } finally{
            logger.flush();
        }

    }

}