b2c/sfsc/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SFCC_Customer_Id__c</fullName>
        <description>This field holds salesforce commerce cloud customer id. Usually case will be connected to contact but this field is to cover edge cases.</description>
        <inlineHelpText>This field holds salesforce commerce cloud customer id. Usually case will be connected to contact but this field is to cover edge cases.</inlineHelpText>
        <label>SFCC Customer Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds commerce cloud customer number</description>
        <inlineHelpText>This field holds commerce cloud customer number</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

b2c/sfsc/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SFCC_Customer_Id__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Customer ID.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Customer ID.</inlineHelpText>
        <label>SFCC Customer Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud customer number.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud customer number.</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

b2c/sfsc/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SFCC_Order_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Order Number.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Order Number.</inlineHelpText>
        <label>Customer Order Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Shipment_Status__c</fullName>
        <description>Status of the progress of the order</description>
        <label>Shipment Status</label>
        <type>Picklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>not_shipped</fullName>
                </value>
                <value>
                    <fullName>shipped</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
</CustomObject>

b2c/sfsc/src/classes/SCCCancelledOrderCompController_Test.cls
@isTest
public class SCCCancelledOrderCompController_Test {

    @testSetup  
    static void setup() {
        SCCTestDataFactory.createSFCCConfigDefaultCustomSetting();
        SCCTestDataFactory.createSFCCCredentialDefaultCustomSetting();    	
        SCCTestDataFactory.createSFCCLogDefaultCustomSetting();  
        SCCTestDataFactory.createContact(new Map<Integer, String>{1=>'fname', 2=>'fname', 3=>'fname'}, new Map<Integer, String>{1=>'lname', 2=>'lname', 3=>'lname'}, new Map<Integer, String>{1=>'test@hotmail.com', 2=>'test@yahoo.com', 3=>'test@salesforce.com'});
        SCCTestDataFactory.createAccount(new Map<Integer, String>{1=>'fname', 2=>'fname', 3=>'fname'}, new Map<Integer, String>{1=>'lname', 2=>'lname', 3=>'lname'}, new Map<Integer, String>{1=>'test@hotmail.com', 2=>'test@yahoo.com', 3=>'test@salesforce.com'}, new Map<Integer, String>{1=>'12345', 2=>'23456', 3=>'34567'}); 
        SCCTestDataFactory.createFieldMappingCustomSettings(new Map<String, String>{'first_name'=>'FirstName', 'last_name'=>'LastName', 'enabled'=>'Active__c', 'email'=>'personEmail', 'birthday'=>'personBirthDate', 'customer_no'=>'SFCC_Customer_Number__pc', 'customer_id'=>'SFCC_Customer_Id__pc'}, 'Account');    
        SCCTestDataFactory.createFieldMappingCustomSettings(new Map<String, String>{'first_name'=>'FirstName', 'last_name'=>'LastName', 'enabled'=>'Active__c', 'email'=>'Email', 'birthday'=>'BirthDate', 'customer_no'=>'SFCC_Customer_Number__c', 'customer_id'=>'SFCC_Customer_Id__c'}, 'Contact'); 
        SCCTestDataFactory.createAccountCase(1, [select Id from Account Limit 1].Id, 'Test Case Description', 'ContactUs', 'Test Case Title');
        SCCTestDataFactory.createCase(1, [select Id from Contact Limit 1].Id, 'Test Case Description', 'ContactUs', 'Test Case Title');    
        SCCTestDataFactory.createOrder(5, [SELECT Id FROM Account LIMIT 1].Id, System.today(), 'Draft', '12345', [SELECT Id FROM Contact LIMIT 1].Id);   
        SCCTestDataFactory.createAccount(1, 'Default', false);        
    }
    
    @isTest
    private static void testCheckOrderStatus_One(){
    	Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('OrderDetails'));         
        Order order = [SELECT Id, SFCC_Order_Number__c FROM Order LIMIT 1];
        Test.startTest();
		SCCCancelledOrderComponentController.checkOrderStatus(order.Id);   
        Test.stopTest();         
    }
    
    @isTest
    private static void testCheckOrderStatus_Two(){
    	Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('OrderDetails'));         
        Order order = [SELECT Id, SFCC_Order_Number__c FROM Order LIMIT 1];
        order.Shipment_Status__c = 'shipped';
        Database.upsert(order);
        Test.startTest();
		SCCCancelledOrderComponentController.checkOrderStatus(order.Id);   
        Test.stopTest();         
    }    
    
    @isTest
    private static void testCheckOrderStatus_Three(){
    	Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('OrderDetails'));         
        Test.startTest();
		SCCCancelledOrderComponentController.checkOrderStatus('fakeId');   
        Test.stopTest();         
    }    
    

    @isTest
    private static void testCancelledOrder_One(){
    	Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('OrderDetails'));         
        Order order = [SELECT Id, SFCC_Order_Number__c FROM Order LIMIT 1];
        Test.startTest();
		SCCCancelledOrderComponentController.cancelledOrder(order.Id);   
        Test.stopTest();         
    }    
    
    @isTest
    private static void testCancelledOrder_Three(){
    	Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('OrderDetails'));         
        Test.startTest();
		SCCCancelledOrderComponentController.cancelledOrder('fakeId');   
        Test.stopTest();         
    }     
}