b2c/sfsc/src/objects/Case.object
<CustomObject>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds commerce cloud customer number</description>
        <inlineHelpText>This field holds commerce cloud customer number</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
    </fields>
</CustomObject>

b2c/sfsc/src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>SFCC_Customer_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud customer number.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud customer number.</inlineHelpText>
        <label>SFCC Customer Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

b2c/sfsc/src/classes/SCCContactImpl_Test.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
public class SCCContactImpl_Test {


    @testSetup 
    static void setup() {
        SCCTestDataFactory.createSFCCConfigDefaultCustomSetting();
        SCCTestDataFactory.createSFCCCredentialDefaultCustomSetting();    	
        SCCTestDataFactory.createSFCCLogDefaultCustomSetting();  
        SCCTestDataFactory.createContact(new Map<Integer, String>{1=>'fname', 2=>'fname', 3=>'fname'}, new Map<Integer, String>{1=>'lname', 2=>'lname', 3=>'lname'}, new Map<Integer, String>{1=>'test@hotmail.com', 2=>'test@yahoo.com', 3=>'test@salesforce.com'});
        SCCTestDataFactory.createAccount(new Map<Integer, String>{1=>'fname', 2=>'fname', 3=>'fname'}, new Map<Integer, String>{1=>'lname', 2=>'lname', 3=>'lname'}, new Map<Integer, String>{1=>'test@hotmail.com', 2=>'test@yahoo.com', 3=>'test@salesforce.com'}, new Map<Integer, String>{1=>'12345', 2=>'23456', 3=>'34567'}); 
        SCCTestDataFactory.createFieldMappingCustomSettings(new Map<String, String>{'first_name'=>'FirstName', 'last_name'=>'LastName', 'enabled'=>'Active__c', 'email'=>'personEmail', 'birthday'=>'personBirthDate'}, 'Account');    
        SCCTestDataFactory.createAccountCase(1, [select Id from Account Limit 1].Id, 'Test Case Description', 'ContactUs', 'Test Case Title');
        SCCTestDataFactory.createCase(1, [select Id from Contact Limit 1].Id, 'Test Case Description', 'ContactUs', 'Test Case Title');        
    }
    
    @isTest
    static void testContinueWithObject_One(){
        Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('CustomerDetails'));
        Contact cont = [select Id from Contact limit 1];
        Test.startTest();
        (new SCCContactImpl()).continueWithObject((SObject)cont);  
        Test.stopTest();
    }

    @isTest
    static void testContinueWithObject_Two(){
        Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('CustomerDetailsWithAddress'));
        Contact cont = [select Id from Contact limit 1];
        Test.startTest();
        (new SCCContactImpl()).continueWithObject((SObject)cont);  
        Test.stopTest();
    }

    @isTest
    static void testContinueWithObject_Three(){
        Contact cont = [select Id from Contact limit 1];
        Test.startTest();
        (new SCCContactImpl()).continueWithObject((SObject)cont);  
        Test.stopTest();
    }
    
    @isTest
    private static void testUpsertAddressBook_One() { 
        String addressBody = '[{"_type" : "customer_address","address1" : "10 Presidential Way","address_id" : "mea","city" : "Woburn","country_code" : "US","first_name" : "John","full_name" : "John M. Smith","last_name" : "Smith","postal_code" : "018.3","salutation" : "Mr.","state_code" : "MA"},';
   	    addressBody += '{"_type" : "customer_address","address1" : "10 Presidential Way","address_id" : "meb","city" : "Woburn","country_code" : "US","first_name" : "John","full_name" : "John M. Smith","last_name" : "Smith","postal_code" : "018.3","salutation" : "Mr.","state_code" : "MA"}]';		
		List<Object> testAddressObj = (List<Object>)System.JSON.deserializeUntyped(addressBody);
        Contact cont = [SELECT Id, SFCC_Customer_Number__c FROM Contact LIMIT 1];
		SCCContactImpl.upsertAddressBook(cont.Id, testAddressObj);   
    }
    
    @isTest
    private static void testUpsertAddressBook_Two() { 
        String addressBody = '[{"_type" : "customer_address","address1" : "10 Presidential Way","city" : "Woburn","country_code" : "US","first_name" : "John","full_name" : "John M. Smith","last_name" : "Smith","postal_code" : "018.3","salutation" : "Mr.","state_code" : "MA"},';
   	    addressBody += '{"_type" : "customer_address","address1" : "10 Presidential Way","address_id" : "meb","city" : "Woburn","country_code" : "US","first_name" : "John","full_name" : "John M. Smith","last_name" : "Smith","postal_code" : "018.3","salutation" : "Mr.","state_code" : "MA"}]';		
		List<Object> testAddressObj = (List<Object>)System.JSON.deserializeUntyped(addressBody);
        Contact cont = [SELECT Id, SFCC_Customer_Number__c FROM Contact LIMIT 1];
		SCCContactImpl.upsertAddressBook(null, testAddressObj);   
    }     
}