b2c/sfsc/src/objects/Order.object
<CustomObject>
    <fields>
        <fullName>SFCC_Order_Number__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Order Number.</description>
        <externalId>true</externalId>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Order Number.</inlineHelpText>
        <label>Customer Order Number</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>SFCC_Order_Total__c</fullName>
        <description>This field holds Salesforce Commerce Cloud Order total value.</description>
        <inlineHelpText>This field holds Salesforce Commerce Cloud Order total value.</inlineHelpText>
        <label>Order Total</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
</CustomObject>

b2c/sfsc/src/classes/SCCOrderDetailPageControllerTest.cls
@isTest 
private class SCCOrderDetailPageControllerTest {

    @testSetup 
    static void setup() {

        SCCTestDataFactory.createSFCCConfigDefaultCustomSetting();
        SCCTestDataFactory.createSFCCCredentialDefaultCustomSetting();      
        SCCTestDataFactory.createSFCCLogDefaultCustomSetting(); 
        SCCTestDataFactory.createContact(new Map<Integer, String>{1=>'fname', 2=>'fname', 3=>'fname'}, new Map<Integer, String>{1=>'lname', 2=>'lname', 3=>'lname'}, new Map<Integer, String>{1=>'test@hotmail.com', 2=>'test@yahoo.com', 3=>'test@salesforce.com'});
        SCCTestDataFactory.createAccount(1, 'Default', false);
        SCCTestDataFactory.createSFCCConfigDefaultCustomSetting();
        SCCTestDataFactory.createFieldMappingCustomSettings(new Map<String, String>{'status'=>'status', 'order_no'=>'SFCC_Orde_Number__c', 'order_total'=>'SFCC_Order_Total__c', 'customer_info'=>'Contact__c'}, 'Order');    
        SCCTestDataFactory.createOrder(5, [SELECT Id FROM Account LIMIT 1].Id, System.today(), 'Draft', '12345', [SELECT Id FROM Contact LIMIT 1].Id);      
    
    }
    
    @isTest
    static void test_method_one() {

        Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test()); 
        Test.startTest();
        Order c = [SELECT Id, SFCC_Order_Number__c FROM Order LIMIT 1];
        ApexPages.StandardController std = new ApexPages.StandardController(c);
        SCCOrderDetailPageController handler = new SCCOrderDetailPageController(std);       
        List<SCCOrderDetailPageController.OrderWrapper> inner_handler = handler.getOrders();
        Test.stopTest();

    }

    @isTest
    static void test_method_two() {

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new SCCHttpCalloutMockGenerator_Test('OrderDetails'));
        Order c = [SELECT Id, SFCC_Order_Number__c FROM Order LIMIT 1];
        ApexPages.StandardController std = new ApexPages.StandardController(c);
        SCCOrderDetailPageController handler = new SCCOrderDetailPageController(std);
        List<SCCOrderDetailPageController.OrderWrapper> inner_handler = handler.getOrders();
        Test.stopTest();

    }

    @isTest
    static void test_method_three() {

        Test.startTest();
        Order c = [SELECT Id, SFCC_Order_Number__c FROM Order LIMIT 1];
        c.SFCC_Order_Number__c = '';
        ApexPages.StandardController std = new ApexPages.StandardController(c);
        SCCOrderDetailPageController handler = new SCCOrderDetailPageController(std);
        Test.stopTest();

    }

}